services:

  redis:
    image: redis:7-alpine
    container_name: gomailer-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  gomailer:
    build: .
    container_name: gomailer
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "8080:8080"

volumes:
  redis_data: